title: UberLyfter
subtitle: "."
description: ""
author: UberLyfter
language: en
timezone: UTC

url: https://www.uberlyfter.com
root: /
permalink: blog/:title/
archive_dir: blog
code_dir: downloads/code
new_post_name: :title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname:
google_analytics:
twitter:

skip_render:
  - source/_redirects

include:
  - source/_redirects
  - _redirects