[build]
  command = "hexo generate"
  publish = "/public"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"