[build]
  command = "hexo generate"
  publish = "/public"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' *.googletagmanager.com *.google-analytics.com api.googleapis.com *.googletagservices.com jobs2careers.com"
    X-Content-Security-Policy = "script-src 'self' 'unsafe-inline' *.googletagmanager.com *.google-analytics.com api.googleapis.com *.googletagservices.com jobs2careers.com"
    Referrer-Policy = "strict-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"