<section id="widget">
  <div id="ad_thread"></div>
</section>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- native_driver_right -->
<ins class="adsbygoogle"
     style="display:inline-block;width:263px;height:700px"
     data-ad-client="ca-pub-9628061608401614"
     data-ad-slot="8405432823"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>