<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} {{ config.author }}. This site is not owned or operated by Uber or Lyft.<br>
    </div>
    <div id="footer-links">
    	<a href="/about/">About</a>|<a href="/privacy/">Privacy</a>|<a href="/terms/">Terms</a>|<a href="/contact/">Contact</a>
    </div>
  </div>
</footer>
