<header id="header" class="wrapper">
  <div id="header-inner" class="inner">
    <div id="logo-wrap">
      <a href="{{ url_for_lang('') }}" id="logo">UberLyfter</a>
    </div>
    <nav id="main-nav">
      {{ header_menu('main-nav') }}
    </nav>
    <a id="mobile-nav-toggle">
      <span class="mobile-nav-toggle-bar"></span>
      <span class="mobile-nav-toggle-bar"></span>
      <span class="mobile-nav-toggle-bar"></span>
    </a>
  </div>
</header>
