<header id="banner" class="wrapper">
  <div class="inner">
    <h1 id="banner-title">{{ page.subtitle }}</h1>
    <div id="banner-start"></div>
  </div>
</header>
<div id="content-wrap" role="main">
  <div class="wrapper">
    <div class="inner">
      {{ page.content }}

      <div id="intro-get-started-wrap">
        <a href="#" id="intro-get-started-link">{{ __('index.get_started') }}</a>
      </div>
    </div>
  </div>
</div>